// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vncixydcygzvqpudkozf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuY2l4eWRjeWd6dnFwdWRrb3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjgyOTMsImV4cCI6MjA1ODI0NDI5M30.8CB2VdgCs8K_GH4UFOe2OaRxewD8Hy_7mCo7YoHAdME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);